### ISSUE TITLE
Occurs when in html mode.  TypeError: Cannot read properties of undefined (reading 'ownerDocument')

### ISSUE THREAD

**Issue by logic3code** [generoi/wp-gutenberg-fontawesome-icon#1]
hello! First of all thank you for this wonderful program.

However, it crashes when the block is set to html mode.

Is there any way to resolve this?

`TypeError: Cannot read properties of undefined (reading 'ownerDocument')`

![message](https://user-images.githubusercontent.com/9914166/182265051-064d170d-cd22-4a83-a5e7-a01ab8cffc13.png)

https://user-images.githubusercontent.com/9914166/182265068-a34b7d83-00ac-436f-abb7-67464ce6eebc.mov

Attach images and videos.

Thank you.

**Comment by oxyc** [comment]
Hi, thanks for the report!

Any chance you could test the latest master branch before I tag a new version?

**Comment by logic3code** [comment]
Great! It has been completely fixed.
appreciate. thank you!
